### ISSUE TITLE
What is the biggest gripe you have with the ui of software you use daily?

### ISSUE THREAD

**Issue by james-gibson** [jackrugile/ama#1]
And have you considered rewriting the ui to support your use case.

**Comment by jackrugile** [comment]
I use a small set of tools daily and for the most part I am completely satisfied with them. The majority of the walls I hit in productivity are my own fault, not the fault of the software I use. For example, I see the bottom of my coffee cup, the panic ensues, and I need to get up and get another before I can focus again.

However, if I had to name one software gripe, it would definitely be Chrome's tab system. As amazing as it is, I think it can be improved in a few ways:

## Rich Previews on Hover

I end up in the tab weeds frequently throughout my day. I'm talking 25-30+ tabs open at once while doing research and what have you. It gets to the point where you can't even see the favicons anymore.

![tab-weeds](https://cloud.githubusercontent.com/assets/726153/19467930/3eaed2ec-94d1-11e6-80db-d9d377caac25.png)

It would be great to be able to hover over each tab and see a small snapshot of the page and the title immediately. That way I could know what I was clicking on without having to do any guessing.

## Ctrl / Cmd + Click Selection for Ordering / Collapsing / Expanding

It would be awesome to be able to select multiple distinct tabs and break them out from where they are currently ordered as a group. For example, what if I wanted to group both of my Twitter tabs together and drag them over to the far left. This doesn't quite work right now. I can select, but not drag together.

![tabs-click](https://cloud.githubusercontent.com/assets/726153/19468282/b975f59a-94d2-11e6-90fc-72d682b56bb8.gif)

Similarly, if these tabs could collapse into a single tab that could be expandable later on, that would be even better. The stacks could could hold similar content together and be tucked away temporarily while working on other things. You might say that opening a new Chrome window with a separate set of tabs is a solution, but it doesn't feel right. It can be unwieldy to separate out the tabs by similarity in their own windows. And, I just don't want multiple windows!

## Tab Age / Expiration Conditions

This one is weird, I'll admit, but I'd find it useful. It would be nice to be able to set your own age definitions for when tabs change freshness. This would allow you to keep focus on what's important and clean things up that you haven't touched throughout the day.
- **00:00 - 00:30** / Fresh
- **00:30 - 01:00** / Turning
- **01:00 - 02:00** / Rotting
- **02:00+** / Dead (Refresh or close this tab, damn it!)

These freshness levels could be indicated by icons or color.

## 

I know there are Chrome extensions that address some of these issues, but they're not quite what I need. I've never written a Chrome extension, but as far as I know, there are some parts of the UI that can't be tapped into, so we're at the mercy of the browser developers. Let me know if I'm wrong on that one.

Or, I can just learn to focus like a normal human.

**Comment by dannyfritz** [comment]
For dragging as a group you can probably try this as a little work around. Select multiple tabs, drag them both downward into a new window, drag them together back into the original window.

**Comment by jackrugile** [comment]
@dannyfritz That just blew my mind. I have no idea how I haven't tried that before. That's a good middle ground. Thanks!
