### ISSUE TITLE
What's your earliest memory?

### ISSUE THREAD

**Issue by sreynen** [jackrugile/ama#5]

**Comment by jackrugile** [comment]
I haven't thought about this in a long time. My earliest memory is pretty mundane. I'll keep it nice and truthful and boring :)

I was living in California and at preschool. There was a chubby, somewhat pasty kid playing with building blocks. He was hogging them and actively blocking another kid from playing with them. After some minutes, the kid who couldn't play snuck up behind the meanie and knocked down his tower. The mean kid burst into tears and went to tell on the other kid.

That's honestly all I remember, nothing juicy, just a vague image in my mind.

![194f023](https://cloud.githubusercontent.com/assets/726153/20028885/d42ad368-a302-11e6-8049-8eee931ccb1d.jpg)
