### ISSUE TITLE
Why do you do $ = this;?

### ISSUE THREAD

**Issue by sistemd** [jackrugile/ama#9]
Seems like most people use either self = this or this_ = this. Why the $?

**Comment by jackrugile** [comment]
Hey @ennmichael,

I forget where I saw it, but I saw it in someone else's code and adopted it for a bit. It seemed like a nice one character convenience that stood out from the rest, but I no longer do it now. It seems to cause more confusion with the popularity of jQuery, and it isn't needed as much with the way I write these days.

So, I did it for no good reason :)
